version: 2
jobs:
  build:
    docker:
      - image: jrottenberg/ffmpeg:4.2-alpine
    working_directory: /tmp
    steps:
      - run: $REMOTE_COMMAND
      - store_artifacts:
          path: /tmp/output.mp4
          destination: converted