version: 2
jobs:
  build:
    docker:
      - image: opencoconut/ffmpeg
      
    steps:
      - checkout
      - run: "echo 'Hello from ${SOURCE_URL:-???}'"
      - run: "which curl"
      - run: "which ffmpeg"
