version: 2
jobs:
  build:
    docker:
      - image: opencoconut/ffmpeg
      
    steps:
      - run: |
          echo ${REMOTE_COMMAND:-???}
          ${REMOTE_COMMAND:--i http://files.coconut.co.s3.amazonaws.com/test.mp4 -f webm -c:v libvpx -c:a libvorbis - > test.webm}